# Generated by Django 5.2.17 on 2026-09-08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("owner", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("visible", "Visible"),
                            ("verified", "Verified"),
                            ("hidden", "Hidden"),
                        ],
                        default="visible",
                        max_length=16,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_definitions",
                        to="catalog.project",
                    ),
                ),
            ],
            options={
                "ordering": ("project_id", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "name"),
                        name="event_catalog_event_project_name_unique",
                    )
                ],
            },
        ),
    ]
