# Generated by Django 5.2.17 on 2026-09-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('event_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdefinition',
            options={'ordering': ('project_id', 'product_key', 'name')},
        ),
        migrations.RemoveConstraint(
            model_name='eventdefinition',
            name='event_catalog_event_project_name_unique',
        ),
        migrations.AddField(
            model_name='eventdefinition',
            name='product_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddConstraint(
            model_name='eventdefinition',
            constraint=models.UniqueConstraint(fields=('project', 'product_key', 'name'), name='event_catalog_event_project_product_name_unique'),
        ),
    ]
