# Generated by Django 5.2.17 on 2026-09-29 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_catalog", "0003_eventdefinition_last_seen_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPropertyDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("property_name", models.TextField()),
                ("property_name_hash", models.CharField(editable=False, max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("visible", "Visible"),
                            ("verified", "Verified"),
                            ("hidden", "Hidden"),
                        ],
                        default="visible",
                        max_length=16,
                    ),
                ),
                ("observed_non_null_types", models.JSONField(default=list)),
                ("nullable", models.BooleanField(default=False)),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_definitions",
                        to="event_catalog.eventdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ("event_definition_id", "property_name"),
                "indexes": [
                    models.Index(
                        fields=["event_definition", "status", "property_name_hash"],
                        name="event_prop_discovery_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_definition", "property_name_hash"),
                        name="event_prop_definition_unique",
                    )
                ],
            },
        ),
    ]
