# Generated by Django 5.2.17 on 2026-09-16 20:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("uuid", models.UUIDField()),
                ("event", models.CharField(max_length=200)),
                ("distinct_id", models.CharField(max_length=400)),
                ("timestamp", models.DateTimeField()),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("groups", models.JSONField(default=dict)),
                ("properties", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="catalog.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["project", "timestamp"], name="events_project_time_idx"),
                    models.Index(
                        fields=["project", "event", "timestamp"],
                        name="events_project_name_time_idx",
                    ),
                    models.Index(
                        fields=["project", "distinct_id", "timestamp"],
                        name="events_project_actor_time_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "uuid"), name="events_project_uuid_unique"
                    )
                ],
            },
        ),
    ]
