# Generated by Django 5.2.17 on 2026-09-16 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("prefix", models.CharField(editable=False, max_length=32, unique=True)),
                ("secret_hash", models.CharField(editable=False, max_length=64)),
                ("require_product", models.BooleanField(default=False)),
                ("require_account", models.BooleanField(default=False)),
                ("last_used_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_credentials",
                        to="catalog.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
