# Generated by Django 5.2.17 on 2026-09-25 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_type', models.CharField(max_length=80)),
                ('group_key', models.CharField(max_length=400)),
                ('properties', models.JSONField(default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_profiles', to='catalog.project')),
            ],
            options={
                'ordering': ('project_id', 'group_type', 'group_key'),
                'indexes': [models.Index(fields=['project', 'group_type', 'last_seen_at'], name='group_profile_type_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'group_type', 'group_key'), name='group_profile_project_type_key_unique')],
            },
        ),
    ]
